### ISSUE TITLE
Error C2026:string too big, trailing characters truncated

### ISSUE THREAD

**Issue by vladimircheng** [owen-bw/Space-Debris-Tracker#1]
i use your code and try to complier it,but it shows that:string too big, trailing characters truncated     Then i find the file:TLEReader.h .In it,there is a string with 20479 Byte .The string was longer than the limit of 16380 Byte.So how can i sovle it.

**Comment by odevop** [comment]
Hello! The TLEReader.h header nor the TLEReader.cpp source contains a string that long, so I'm not entirely sure why you are getting that error. The TLEReader does extract a very large set of data from the files "2023_332.txt", "2023_337.txt", and"2023_338.txt" (Line 40 of TLEReader.cpp) which could be where your issue is stemming from.

Could you provide a detailed output of your error?

**Comment by vladimircheng** [comment]
yep,this error is in fontCourier20.h,,a string:const unsigned char bitmapCourier20[]  i use clion ,this is its output:
OpenGLEngine.cpp
D:\space\Space-Debris-Tracker\include\fontCourier20.h(205,1): error C2026: The string is too large and the trailing characters have been truncated [D:\space\Space-Debris-Tracker\cmake-build- debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\include\linmath.h(585,18): warning C4244: 'parameter': conversion from 'double' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\include\linmath.h(591,18): warning C4244: 'parameter': conversion from 'double' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(465,55): warning C4244: 'parameter': conversion from 'int' to 'GLfloat', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(466,55): warning C4244: 'parameter': conversion from 'int' to 'GLfloat', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(513,24): warning C4244: 'parameter': conversion from 'int' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(513,21): warning C4244: 'parameter': conversion from 'int' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(601,21): warning C4244: 'initialization': conversion from 'float' to 'int', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(613,19): warning C4244: 'initialization': conversion from 'double' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(614,20): warning C4244: 'initialization': conversion from 'double' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(615,20): warning C4244: 'initialization': conversion from 'double' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(617,18): warning C4244: 'initialization': conversion from 'double' to 'float', possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(795,39): warning C4267: "=": conversion from "size_t" to "int", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(800,52): warning C4244: "=": conversion from "double" to "GLfloat", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(801,56): warning C4244: "=": conversion from "double" to "GLfloat", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(802,56): warning C4244: "=": conversion from "double" to "GLfloat", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(813,39): warning C4267: "=": conversion from "size_t" to "int", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(818,52): warning C4244: "=": conversion from "double" to "GLfloat", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(819,56): warning C4244: "=": conversion from "double" to "GLfloat", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(820,56): warning C4244: "=": conversion from "double" to "GLfloat", possible data loss [D:\space\Space- Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(987,44): warning C4244: "+=": conversion from "double" to "float", possible data loss [D:\space\Space -Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(988,44): warning C4244: "+=": conversion from "double" to "float", possible data loss [D:\space\Space -Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(1001,46): warning C4244: "-=": conversion from "double" to "float", possible data loss [D:\space\Space -Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]
D:\space\Space-Debris-Tracker\src\OpenGLEngine.cpp(1011,41): warning C4244: "-=": conversion from "double" to "float", possible data loss [D:\space\Space -Debris-Tracker\cmake-build-debug-visual-studio\space-debris-tracker.vcxproj]

**Comment by odevop** [comment]
It seems that CLion's compiler may have an incompatibility with the font file I used. This was used to render an FPS counter, so that counter will unfortunately no longer work unless there is a workaround for including a bitmap font in CLion. I removed it and it should no longer give that error.

Let me know if that fixed your issue!

**Comment by vladimircheng** [comment]
I don’t quite understand what you said. Do you mean that I can just use ImGUI instead? Or do you have any good method to compile successfully?

**Comment by odevop** [comment]
Pull the latest version or reclone the repository since I made some changes, then compile using CLion again.

Personally, I use VSCode and CMake Tools to compile this project.

**Comment by vladimircheng** [comment]
thanks,The previous problems have been solved, but there are still some. Sorry to trouble you.
here is that:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: Command "setlocal
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: .\space-debris-tracker
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto : cmDone
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 9009.

**Comment by odevop** [comment]
What operating system and CPU architecture are you using? I'm installing CLion to see if I can replicate your issue.

**Comment by vladimircheng** [comment]
> What operating system and CPU architecture are you using? I'm installing CLion to see if I can replicate your issue.

I use windows10 and my cou is R7-5800H

**Comment by vladimircheng** [comment]
The generator I used before was VS2019. Now after replacing clion’s default ninja, this problem has been solved, but there is still another problem：[28/28] Linking CXX executable space-debris-tracker.exe
FAILED: space-debris-tracker.exe 
cmd.exe /C "cd . && D:\CLION2~1.2\bin\mingw\bin\G__~1.EXE -g  CMakeFiles/space-debris-tracker.dir/include/tle/AstroFuncDll.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/DllMainDll.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/DllMainDll_Service.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/DllUtils.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/EnvConstDll.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/Sgp4PropDll.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/TimeFuncDll.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/TimeFuncDll_Service.c.obj CMakeFiles/space-debris-tracker.dir/include/tle/TleDll.c.obj CMakeFiles/space-debris-tracker.dir/src/BitmapFontData.cpp.obj CMakeFiles/space-debris-tracker.dir/src/Bmp.cpp.obj CMakeFiles/space-debris-tracker.dir/src/Matrices.cpp.obj CMakeFiles/space-debris-tracker.dir/src/OpenGLEngine.cpp.obj CMakeFiles/space-debris-tracker.dir/src/SpaceDebris.cpp.obj CMakeFiles/space-debris-tracker.dir/src/Sphere.cpp.obj CMakeFiles/space-debris-tracker.dir/src/TLEReader.cpp.obj CMakeFiles/space-debris-tracker.dir/src/Timer.cpp.obj CMakeFiles/space-debris-tracker.dir/src/Tokenizer.cpp.obj CMakeFiles/space-debris-tracker.dir/src/gl.c.obj CMakeFiles/space-debris-tracker.dir/src/imgui.cpp.obj CMakeFiles/space-debris-tracker.dir/src/imgui_demo.cpp.obj CMakeFiles/space-debris-tracker.dir/src/imgui_draw.cpp.obj CMakeFiles/space-debris-tracker.dir/src/imgui_impl_glfw.cpp.obj CMakeFiles/space-debris-tracker.dir/src/imgui_impl_opengl3.cpp.obj CMakeFiles/space-debris-tracker.dir/src/imgui_tables.cpp.obj CMakeFiles/space-debris-tracker.dir/src/imgui_widgets.cpp.obj CMakeFiles/space-debris-tracker.dir/src/main.cpp.obj -o space-debris-tracker.exe -Wl,--out-implib,libspace-debris-tracker.dll.a -Wl,--major-image-version,0,--minor-image-version,0  ../lib/windows/libglfw3.a  -lopengl32  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D D:\space\Space-Debris-Tracker-main\build && .\space-debris-tracker""
ninja: build stopped: subcommand failed.   It seems to be a dynamic link issue

**Comment by vladimircheng** [comment]
I read Ninja's log, and it seems that it is a problem with my use of the Windows 10 operating system. Some of the commands use / and some use \. Are you using Ubuntu?

**Comment by odevop** [comment]
I primarily compiled on Mac but it does compile on Windows. I use VSCode and the Cmake Tools extension to compile which may link the executable differently than CLion does. I was able to compile on CLion using my Mac but I did have to make some changes to the CMakeList.txt before I got it to compile. Seems like it could be a similar issue. I will test using CLion on my windows machine later this weekend

**Comment by odevop** [comment]
I've resolved the issue by adding the required DLL files directly into the build directory. For some reason the way that CLion links the DLL files doesn't take into account their relative paths. Now that the DLLs are directly located where the executable goes, you should finally be able to run the executable.

**Comment by vladimircheng** [comment]
thanks very much,I move DLL fiels to build directory too,the reason is probably my PC dosn't have some DLL files ,I am trying to solve it .Once again I would like to express my heartfelt thanks！

**Comment by odevop** [comment]
Awesome! I'm glad you're able to get it working! Let me know if your run into any other issues and feel free to make a pull request if you'd like to add something!
